name: myBlog GitHub Actions
on:
  push:
    branches:
      - master
jobs:
  deploy-githubpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - run: npm install --legacy-peer-deps
      - run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
